theme: jekyll-theme-primer
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
